### ISSUE TITLE
cmake error compiling grasp_pose_generator 

### ISSUE THREAD

**Issue by BoboTheFFClown** [atenpas/gpd#11]
Hi, 

I run into trouble when compiling gpg, see screen shot for error message. I successfully installed Caffe, but from the error message, it looks like a PCL issue. I'm quite confused as to should I build a stand-along pcl package like pcl_ros in current workspace and use it as dependency for the gpg package or would I be fine using ros indigo's built-in libpcl? Thanks in advance for the help.  
![image](https://user-images.githubusercontent.com/30354693/29221507-0b978132-7e8d-11e7-8ef5-38c50086abe1.png)

**Comment by atenpas** [comment]
Here's a possible solution for Ubuntu 14.04 that uses apt-get:
> sudo apt-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl 
> sudo apt-get update 
> sudo apt-get install libpcl-all

**Comment by BoboTheFFClown** [comment]
I am using Ubuntu 14.04. I tried what you suggested, my pcl version is still 1.7 and still fails to compile gpg. Terminal outputs identical error. Sorry I am a newbie, could you elaborate on how to properly configure pcl to get the package working.

**Comment by atenpas** [comment]
What did you try? **apt-get** or cloning the pcl repository?

**Comment by BoboTheFFClown** [comment]
First I did 'sudo apt-get update' then I 'sudo apt-get install libpcl-all'. It failed to make, then I deleted the whole package, and try to cloning the repository 'sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl' and cmake and make, still failed to compile. In both cases, terminal throws same error as before.

**Comment by atenpas** [comment]
When using _apt-get_, you should add the PPA **before** the update and the install.

There are two ways to install PCL: (a) using apt-get as shown above, **or** (b) by cloning pcl's github repository and checking out the 1.7.2 tag/branch.

**Comment by BoboTheFFClown** [comment]
I repeated the process added PPA before doing updates and install, but still doesn't work. I am going to try the cloning. Before doing that, should I do a apt-get autoremove libpcl? I am not quite sure how to install pcl using the cloned repository, can I clone the repo into my current workspace folder and compile it in there with catkin_make?

**Comment by atenpas** [comment]
I cannot tell you as I don't have 14.04 available here. I was assuming that this installs a recent version of PCL because it's suggested as an install method in [PCL's documentation](http://pointclouds.org/downloads/linux.html).

For the github repository, you can find instructions [here](http://pointclouds.org/documentation/tutorials/compiling_pcl_posix.php. ).

**Comment by atenpas** [comment]
@BoboTheFFClown Could you run `dpkg -s libpcl-all` in a terminal? That will show you the version number that is installed.

**Comment by YuehChuan** [comment]
@atenpas , I got same issue. and this is `dpkg -s libpcl-all` output
I'm on fresh install  ubuntu14.04.5  indigo, pcl using  apt-get install 
```bash=
sudo apt-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl
sudo apt-get update
sudo apt-get install libpcl-all
```
I will check it, if got luck to solve it will update here.


![gpd-issue2](https://user-images.githubusercontent.com/7314531/29248534-06384aa2-804d-11e7-8a56-9e54386f0fea.png)




![gpd-issue](https://user-images.githubusercontent.com/7314531/29248530-f0275226-804c-11e7-8558-2fefc7d4966a.png)

**Comment by YuehChuan** [comment]
@BoboTheFFClown , @atenpas  solve the issue.
It's because PCL version problem.
using prebuild PCL binary actually is 1.7.1
check for library /usr/lib  $ ls /usr/lib | grep pcl  you will find it.
```bash=
sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl
sudo apt-get update
sudo apt-get install libpcl-all
```
it's because different name.
for pcl 1.7.2   PointCloudColorHandlerRGBAField
http://docs.pointclouds.org/1.7.2/a01016.html
for pcl 1.7.1  PointCloudColorHandlerRGBField
http://docs.pointclouds.org/1.7.1/classpcl_1_1visualization_1_1_point_cloud_color_handler_r_g_b_field.html

*How to solve it*
inside gpg/src/gpg/plot.cpp  change PointCloudColorHandlerRGBAField to PointCloudColorHandlerRGBField
https://github.com/atenpas/gpg/blob/master/src/gpg/plot.cpp#L31

also here
https://github.com/atenpas/gpg/blob/master/src/gpg/plot.cpp#L38

then `make` succeed.
@atenpas  I think  claim using PCL-1.7.2 more specific in README is necessary.
Thanks for opensource the repo.

**Comment by YuehChuan** [comment]
By the way, is it necessary to use GPU in caffe?
I'm using orbbec astra RGBD camera, but my laptop no no GPU.
thank you

![gpdrviz](https://user-images.githubusercontent.com/7314531/29249043-edfe9024-8059-11e7-81ef-1066f46f565d.png)
![gpd-issue](https://user-images.githubusercontent.com/7314531/29249044-f09bc306-8059-11e7-9c2f-ac0995d821c5.png)

**Comment by atenpas** [comment]
@YuehChuan Does changing PointCloudColorHandlerRGBAField to PointCloudColorHandlerRGBField remove the transparency? Anyway, I guess I'll just change it back to PointCloudColorHandlerRGBField because that seems to be the most compatible way (and the transparency is not that important).

To make Caffe use the CPU, you need to change [this parameter](https://github.com/atenpas/gpd/blob/master/launch/caffe/classifier_15channels.launch#L8).

**Comment by YuehChuan** [comment]
@atenpas , thank you! COOOL
![arcc](https://user-images.githubusercontent.com/7314531/29253565-184efb08-80b3-11e7-9f82-c0b148c8f030.png)
this is what i got in rviz, 
for pcl visualiazation, i could not find launch/openni2_15_channels.launch to see  transparency. 
By the way, are there parameters we could adjust?
Thanks for make this repo available, habonbon!

my environment  lenovo x220 laptop i5, ubuntu14.04.5, ros indigo , pcl-1.7.1 by apt-get install

**Comment by atenpas** [comment]
@YuehChuan The two most important parameters are probably _num_samples_ and _workspace_. I'm closing this issue now. If you have specific questions about parameters, feel free to shoot me an email!

**Comment by YuehChuan** [comment]
@atenpas thank you!
